#pragma config(Sensor, in1,    Pot,            sensorPotentiometer)
#pragma config(Sensor, in2,    LineTrack1,     sensorLineFollower)
#pragma config(Sensor, in3,    LineTrack2,     sensorLineFollower)
#pragma config(Sensor, in4,    LineTrack3,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  Quad,           sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftWheelMotor1, tmotorVex393, openLoop)
#pragma config(Motor,  port2,           RightWheelMotor2, tmotorVex393, openLoop)
#pragma config(Motor,  port3,           LeftClawMotor3, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           RightClawMotor4, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           RampMotor5,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


// Move forward (LeftWheelMotor and RightWheel Motor forward) when sees linetrack at X1 speed
wait1Msec(3000);

while (1 == 1)
{SensorValue[2] = 127;
SensorValue[3] = 0;
SensorValue[4] = 127;
	
motor[LeftWheelMotor1] = -80;
motor[RightWheelMotor2] = -80;
motor[LeftClawMotor3] = 127; // claw open
motor[RightClawMotor4] = 127;// claw open}
}


//when gradient changes, move to new speed (slower speed; X2) or else continue
// with first speed X1

if (SensorValue[1]== 0) 
{motor[LeftWheelMotor1] = -80;
	motor[RightWheelMotor2] = -80;}
else 
{motor[LeftWheelMotor1] = -40;
	motor[RightWheelMotor2] = -40;}

	// when hit perpendicular line ie when all the line trackers sense black robot stop and claw close



while (1 == 1)
	
{SensorValue[2] = 0; 
SensorValue[3] = 0; 
SensorValue[4] = 0;


motor[LeftWheelMotor1] = 0; // left motor wheel stop
motor[RightWheelMotor2] = 0; // right motor wheel stop
motor[LeftClawMotor3] = -127; // left motor close
motor[RightClawMotor4] = -127; // right motor close 
}


//when claws (LeftClawMotor and RightClawMotor) close, robot goes from
//autonomous to manual/remote control

while (1 == 1)
{
	motor[LeftWheelMotor1] = vexRT[Ch1] / 2;
	motor[RightWheelMotor2] =vexRT[Ch2] / 2;
	motor[LeftClawMotor3] = vexRT[Ch3] /2;
	motor[RightClawMotor4] = vexRT[Ch4] / 2;
	motor[RampMotor5] = vexRT[Ch5] / 2;
}

//when button is pushed for LeftClawMotor and RightClawMotor 
//the claws open to release robot from bar




// button Ball Drop is pushed, the Ball drop device is activated and ball drops
// after three seconds Motor stop

}