pragma config(Sensor, in1,    Pot1,           sensorPotentiometer)
#pragma config(Sensor, in2,    LineTrack1,     sensorLineFollower)
#pragma config(Sensor, in3,    LineTrack2,     sensorLineFollower)
#pragma config(Sensor, in4,    LineTrack3,     sensorLineFollower)
#pragma config(Motor,  port1,           LeftWheelMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port2,           RightWheelMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port3,           LeftClawMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           RightClawMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	

// Move forward (LeftWheelMotor and RightWheel Motor forward) when sees linetrack at X1 speed





//when gradient changes, move to new speed (slower speed; X2) or else continue
// with first speed X1





//when hits curvy line, switch to accurate threshold T2; if not stay on
//straight line threshold of T1





//when hit perpendicular line ie. when all the line trackers sense black
//robot stop





//when robot stops, claws (LeftClawMotor and RightClawMotor) closes




//when claws (LeftClawMotor and RightClawMotor) close, robot goes from
//autonomous to manual/remote control




//when button is pushed for LeftClawMotor and RightClawMotor 
//the claws open to release robot from bar





//when button Ball Drop is pushed, the Ball drop device is activated and ball drops




}