#pragma config(Sensor, in1,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, dgtl1,  quad,           sensorNone)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           LeftClaw,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           RightClaw,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           Ramp6,         tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	    - Triple Sensor Line Tracking -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses 3 VEX Line Follower Sensors to track a black line on a light(er) surface.       *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Lighting conditions, line darkness, and surface lightness change from place to place,       *|
|*        so the value of 'threshold' may need to be changed to better suit your environment.         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 1     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down          *|
|*    Analog - Port 2     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down         *|
|*    Analog - Port 3     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down           *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  wait1Msec(2000);          // The program waits for 2000 milliseconds before continuing.

  int threshold = 505;      /* found by taking a reading on both DARK and LIGHT    */
                            /* surfaces, adding them together, then dividing by 2. */
  while(true)
  {

    // RIGHT sensor sees dark:
    if(SensorValue(lineFollowerRIGHT) > threshold)
    {
      // counter-steer right:
      motor[LeftMotor]  = 63;
      motor[RightMotor] = 0;
    }
    // CENTER sensor sees dark:
    if(SensorValue(lineFollowerCENTER) > threshold)
    {
      // go straight
      motor[LeftMotor]  = 63;
      motor[RightMotor] = 63;
    }
    // LEFT sensor sees dark:
    if(SensorValue(lineFollowerLEFT) > threshold)
    {
      // counter-steer left:
      motor[LeftMotor]  = 0;
      motor[RightMotor] = 63;
    }
    
  
  if(SensorValue(lineFollowerRIGHT) && (SensorValue(lineFollowerLEFT) && SensorValue(lineFollowerRIGHT)< threshold))
  	{
    	motor[LeftMotor] = 0;
      motor[RightMotor] = 0;
      motor[LeftClaw] = 127;
      motor[RightClaw] = 127;
    
    }
}

  
 
	while(time1[T1] < 30000)
	
{
	motor[LeftMotor] = vexRT[Ch1] / 2;
	motor[RightMotor] =vexRT[Ch2] / 2;
	motor[LeftClaw] = vexRT[Ch3] /2;
	motor[RightClaw] = vexRT[Ch4] / 2;
	motor[Ramp6] = vexRT[Ch5] / 2;
	
	// if group 5 button up pressed, claw opens or closes
	
	if(vexRT[Btn5U] == 1)
	{
		{motor[LeftClaw] = 127;
		motor[RightClaw] = 127;}
	}
	else if (vexRT[Btn5D] == 1)
	{
		{motor[LeftClaw] = -127;
		motor[RightClaw] = -127;}
	}
	else
	{
		{motor[LeftClaw] = 0;
		motor[RightClaw] = 0;}
	}
	
	// if group 6 button up pressed, ramp goes up or goes down or else doesn't move
	
	if (vexRT[Btn6U] == 1)
	{
		motor[Ramp6] = 60;
	}
	else if (vexRT[Btn6D] == 1)
	{
		motor[Ramp6] = -60;
	}
	else
	{
		motor[Ramp6] = 0;}
	}
	
}