#pragma config(Sensor, dgtl1,  angleSensor,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorSONAR_cm)
#pragma config(Motor,  port2,           scanMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	// initialize variables for current and target angles
	int current_angle = 0;
	int target_angle = 0;

	// initialize variable to use in FOR loop
	int i = 0;

	// loop through 9 times for a total of 10 measurements (0 through 9)
	for (i = 0; i < 9; i++)
	{
		// read the current potentiometer value and save it to a variable
		current_angle = SensorValue(angleSensor);

		// wait 5 seconds so you can read the sonar sensor value off the screen
		wait1Msec(5000);

		// set the target angle to the current angle + some number (you will have to determine this by trial and error)
		target_angle = current_angle + 10;

		// run the motor until the potentiometer reads the same value as the target angle
		while (SensorValue(angleSensor) < target_angle)
		{
			motor[scanMotor] = 25;
		}
		motor[scanMotor] = 0;

	}





}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++